name: Detect PUML File Changes

on: [push]

jobs:
  check-puml:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get all changed PUML files
      id: changed-puml-files
      uses: tj-actions/changed-files@v44
      with:
        # Avoid using single or double quotes for multiline patterns
        files: |
          **/*.puml

    - name: List all changed PUML files
      if: steps.changed-puml-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-puml-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done